// ── Vibe's engine ─────────────────────────────────────────────────────────
// GENERATED by C:/Vibe/web/build-runningboy.js — do not edit here.
// The source lives in C:/Vibe/web/engine/, where it is checked byte-for-byte
// against the original 2010 app running on a JVM. Edit there and rebuild.
//
// This is the song model, the .vbm file format and the MIDI exporter from
// Vibe, plus a small Web Audio synth standing in for the phone's GM chip.
// Flattened out of ES modules because Running Boy uses classic scripts.

// ===== instruments.js =====
// The General MIDI instrument names, as Vibe listed them. Lifted from the
// original's own table (ae.class) so the numbering matches exactly.
const GM = [
'Acoustic Grand Piano','Bright Acoustic Piano','Electric Grand Piano','Honky-tonk Piano',
'Electric Piano 1','Electric Piano 2','Harpsichord','Clavinet',
'Celesta','Glockenspiel','Music Box','Vibraphone','Marimba','Xylophone','Tubular Bells','Dulcimer',
'Drawbar Organ','Percussive Organ','Rock Organ','Church Organ','Reed Organ','Accordion','Harmonica','Tango Accordion',
'Acoustic Guitar (nylon)','Acoustic Guitar (steel)','Electric Guitar (jazz)','Electric Guitar (clean)',
'Electric Guitar (muted)','Overdriven Guitar','Distortion Guitar','Guitar Harmonics',
'Acoustic Bass','Electric Bass (finger)','Electric Bass (pick)','Fretless Bass',
'Slap Bass 1','Slap Bass 2','Synth Bass 1','Synth Bass 2',
'Violin','Viola','Cello','Contrabass','Tremolo Strings','Pizzicato Strings','Orchestral Harp','Timpani',
'String Ensemble 1','String Ensemble 2','Synth Strings 1','Synth Strings 2',
'Choir Aahs','Voice Oohs','Synth Voice','Orchestra Hit',
'Trumpet','Trombone','Tuba','Muted Trumpet','French Horn','Brass Section','Synth Brass 1','Synth Brass 2',
'Soprano Sax','Alto Sax','Tenor Sax','Baritone Sax','Oboe','English Horn','Bassoon','Clarinet',
'Piccolo','Flute','Recorder','Pan Flute','Blown Bottle','Shakuhachi','Whistle','Ocarina',
'Lead 1 (square)','Lead 2 (sawtooth)','Lead 3 (calliope)','Lead 4 (chiff)',
'Lead 5 (charang)','Lead 6 (voice)','Lead 7 (fifths)','Lead 8 (bass + lead)',
'Pad 1 (new age)','Pad 2 (warm)','Pad 3 (polysynth)','Pad 4 (choir)',
'Pad 5 (bowed)','Pad 6 (metallic)','Pad 7 (halo)','Pad 8 (sweep)',
'FX 1 (rain)','FX 2 (soundtrack)','FX 3 (crystal)','FX 4 (atmosphere)',
'FX 5 (brightness)','FX 6 (goblins)','FX 7 (echoes)','FX 8 (sci-fi)',
'Sitar','Banjo','Shamisen','Koto','Kalimba','Bagpipe','Fiddle','Shanai',
'Tinkle Bell','Agogo','Steel Drums','Woodblock','Taiko Drum','Melodic Tom','Synth Drum','Reverse Cymbal',
'Guitar Fret Noise','Breath Noise','Seashore','Bird Tweet','Telephone Ring','Helicopter','Applause','Gunshot',
];


// ===== synth.js =====
// ── A synth, because the browser does not come with one ───────────────────
// Vibe never had to solve this: it called device://midi and the phone's own
// General MIDI chip made the sound. A browser gives you oscillators and
// nothing else, so the instruments have to be built.
//
// This is deliberately small — oscillators, a filter and an envelope, with
// the settings chosen per GM family. It is not a soundfont and does not
// pretend to be: a trumpet here is a bright sawtooth, not a trumpet. What it
// buys is an app that loads instantly, works offline and needs no samples,
// which is the right trade while the editor is the thing being worked on.
//
// Swapping in real samples later means replacing `voice()` and nothing else.

/// GM programs are laid out in families of eight, which is handy: the family
/// decides the waveform and the brightness.
function familyOf(program) {
    if (program < 8)   return 'piano';
    if (program < 16)  return 'bell';
    if (program < 24)  return 'organ';
    if (program < 32)  return 'guitar';
    if (program < 40)  return 'bass';
    if (program < 56)  return 'strings';
    if (program < 64)  return 'brass';
    if (program < 80)  return 'reed';
    if (program < 96)  return 'lead';
    if (program < 104) return 'pad';
    if (program < 112) return 'ethnic';
    return 'percussive';
}

const VOICES = {
    //          wave        attack  decay  sustain  release  cutoff  detune
    piano:      ['triangle', 0.002, 0.22,  0.25,  0.30,  4200,  0],
    bell:       ['sine',     0.001, 0.60,  0.05,  0.80,  6000,  3],
    organ:      ['square',   0.010, 0.05,  0.85,  0.12,  2600,  0],
    guitar:     ['sawtooth', 0.004, 0.30,  0.20,  0.25,  3000,  4],
    bass:       ['sawtooth', 0.006, 0.18,  0.55,  0.18,  900,   0],
    strings:    ['sawtooth', 0.090, 0.20,  0.80,  0.40,  2200,  6],
    brass:      ['sawtooth', 0.030, 0.12,  0.75,  0.22,  3400,  4],
    reed:       ['square',   0.030, 0.10,  0.80,  0.20,  2400,  2],
    lead:       ['square',   0.005, 0.10,  0.70,  0.18,  3800,  5],
    pad:        ['triangle', 0.200, 0.40,  0.85,  0.90,  1800,  8],
    ethnic:     ['triangle', 0.004, 0.35,  0.15,  0.35,  3200,  3],
    percussive: ['sine',     0.001, 0.30,  0.02,  0.30,  5000,  0],
};

/// Channel 10 (index 9) is the drum kit: the note number picks a sound
/// rather than a pitch.
const DRUMS = {
    35: ['kick', 55], 36: ['kick', 65], 37: ['click', 900],
    38: ['snare', 0], 39: ['clap', 0],  40: ['snare', 0],
    42: ['hat', 0.04], 44: ['hat', 0.06], 46: ['hat', 0.28],
    49: ['crash', 0.9], 51: ['ride', 0.5],
};

class Synth {
    constructor() {
        this.ctx = null;
        this.out = null;
        this.live = new Set();
        this.programs = new Map();      // channel -> GM program
        this._noise = null;
    }

    /// Browsers will not make a sound until a gesture starts the context.
    async start() {
        if (!this.ctx) {
            const AC = window.AudioContext || window.webkitAudioContext;
            this.ctx = new AC();
            this.out = this.ctx.createGain();
            this.out.gain.value = 0.22;                 // headroom for chords
            const squash = this.ctx.createDynamicsCompressor();
            this.out.connect(squash).connect(this.ctx.destination);
        }
        if (this.ctx.state === 'suspended') await this.ctx.resume();
        return this.ctx;
    }

    setProgram(channel, program) { this.programs.set(channel, program); }

    /// One shared buffer of noise, for the drums.
    noise() {
        if (this._noise) return this._noise;
        const n = this.ctx.sampleRate * 0.5;
        const buf = this.ctx.createBuffer(1, n, this.ctx.sampleRate);
        const d = buf.getChannelData(0);
        for (let i = 0; i < n; i++) d[i] = Math.random() * 2 - 1;
        return (this._noise = buf);
    }

    /// Play a note. `seconds` is how long it is held.
    hit(channel, note, velocity = 100, seconds = 0.25) {
        if (!this.ctx) return;
        const t = this.ctx.currentTime;
        const gain = Math.min(1, velocity / 127) * 0.9;
        if (channel === 9) this.drum(note, gain, t);
        else this.voice(this.programs.get(channel) ?? 0, note, gain, seconds, t);
    }

    voice(program, note, gain, seconds, t) {
        const [wave, a, d, s, r, cutoff, detune] = VOICES[familyOf(program)];
        const hz = 440 * Math.pow(2, (note - 69) / 12);

        const env = this.ctx.createGain();
        const filt = this.ctx.createBiquadFilter();
        filt.type = 'lowpass';
        filt.frequency.value = Math.min(cutoff, this.ctx.sampleRate / 2 - 100);
        filt.Q.value = 0.8;

        const oscs = [];
        for (const cents of detune ? [-detune, detune] : [0]) {
            const o = this.ctx.createOscillator();
            o.type = wave;
            o.frequency.value = hz;
            o.detune.value = cents;
            o.connect(filt);
            oscs.push(o);
        }
        filt.connect(env).connect(this.out);

        // Attack, decay to the sustain level, hold, then release.
        const peak = gain / (oscs.length || 1);
        env.gain.setValueAtTime(0.0001, t);
        env.gain.exponentialRampToValueAtTime(Math.max(peak, 0.0002), t + a);
        env.gain.exponentialRampToValueAtTime(Math.max(peak * s, 0.0002), t + a + d);
        const off = t + Math.max(seconds, a + d);
        env.gain.setValueAtTime(Math.max(peak * s, 0.0002), off);
        env.gain.exponentialRampToValueAtTime(0.0001, off + r);

        for (const o of oscs) {
            o.start(t);
            o.stop(off + r + 0.02);
            this.live.add(o);
            o.onended = () => this.live.delete(o);
        }
    }

    drum(note, gain, t) {
        const [kind, arg] = DRUMS[note] || ['hat', 0.05];
        if (kind === 'kick') {
            const o = this.ctx.createOscillator(), g = this.ctx.createGain();
            o.type = 'sine';
            o.frequency.setValueAtTime(arg * 2.6, t);
            o.frequency.exponentialRampToValueAtTime(arg * 0.6, t + 0.11);
            g.gain.setValueAtTime(gain, t);
            g.gain.exponentialRampToValueAtTime(0.0001, t + 0.22);
            o.connect(g).connect(this.out);
            o.start(t); o.stop(t + 0.24);
            return;
        }
        const src = this.ctx.createBufferSource();
        src.buffer = this.noise();
        const g = this.ctx.createGain(), f = this.ctx.createBiquadFilter();
        if (kind === 'snare' || kind === 'clap') {
            f.type = 'bandpass'; f.frequency.value = kind === 'clap' ? 1400 : 1900; f.Q.value = 1.1;
        } else if (kind === 'click') {
            f.type = 'bandpass'; f.frequency.value = arg; f.Q.value = 4;
        } else {
            f.type = 'highpass'; f.frequency.value = kind === 'crash' ? 4000 : 7000;
        }
        const len = kind === 'snare' ? 0.17 : kind === 'clap' ? 0.14
                  : kind === 'click' ? 0.05 : (typeof arg === 'number' ? arg : 0.05);
        g.gain.setValueAtTime(gain * 0.8, t);
        g.gain.exponentialRampToValueAtTime(0.0001, t + len);
        src.connect(f).connect(g).connect(this.out);
        src.start(t); src.stop(t + len + 0.02);
    }

    allOff() {
        for (const o of this.live) { try { o.stop(); } catch (_) {} }
        this.live.clear();
    }
}


// ===== song.js =====
// ── Vibe's engine, ported from the original ───────────────────────────────
// A faithful port of the 2010 J2ME app's song model, its .vbm file format,
// and its MIDI export. Ported from decompiled source and checked
// byte-for-byte against the original code running on a JVM, because a file
// format that is merely plausible is a file format that is wrong.
//
// The names here are the real ones; in the original everything is a single
// obfuscated letter (ah, t, b, j, aj). The mapping, for anyone reading the
// Java alongside this:
//
//   ah -> Song    t -> Riff    b -> Track    j -> Placement    aj -> Event
//
// Vibe's units: a song has `bars` bars per riff, and 16 steps per bar. A
// step is 24 MIDI ticks, so a bar is 384 ticks and a quarter note is 96 —
// which is exactly the division written into the file.

const STEPS_PER_BAR = 16;
const TICKS_PER_STEP = 24;
const NOTE_ON = 144;        // 0x90
const PROGRAM = 192;        // 0xC0

// ── Model ─────────────────────────────────────────────────────────────────

/// One MIDI event inside a riff. `tick` is in steps from the riff's start,
/// `dur` is in steps and only means anything for a note.
class Event {
    constructor(status, data, dur = 0, tick = 0) {
        this.status = status & 0xF0;
        this.data = data;
        this.dur = dur;
        this.tick = tick;
    }
    static note(pitch, velocity, dur, tick = 0) {
        return new Event(NOTE_ON, [pitch & 0xFF, velocity & 0xFF], dur, tick);
    }
    static program(p) { return new Event(PROGRAM, [p & 0xFF], 0, 0); }
    get isNote() { return this.status === NOTE_ON; }
    clone() { return new Event(this.status, this.data.slice(), this.dur, this.tick); }
}

/// A pattern. Riffs are shared: a track places the same riff repeatedly,
/// which is how the original kept the editable grid small.
class Riff {
    constructor(name, bars = 1, id = null) {
        this.name = name;
        this.bars = bars;
        // Identity, not position: placements reference a riff by this, so it
        // has to survive a save. The original seeded it from the clock.
        this.id = id === null ? Riff._nextId() : BigInt(id);
        this.events = [];
    }
    static _seed = BigInt(Date.now());
    static _nextId() { return Riff._seed++; }

    /// Insert in tick order. The original's `b()` does this; its `a()`
    /// REMOVES, which is an easy and expensive thing to get backwards.
    add(ev) {
        const i = this.events.findIndex(e => e.tick >= ev.tick);
        if (i === -1) this.events.push(ev); else this.events.splice(i, 0, ev);
        return ev;
    }
    remove(ev) {
        const i = this.events.indexOf(ev);
        if (i !== -1) this.events.splice(i, 1);
    }
    get steps() { return this.bars * STEPS_PER_BAR; }
}

/// Where a riff sits in a track. `at` counts riffs, not steps.
class Placement {
    constructor(riff, at = 0) { this.riff = riff; this.at = at; }
}

class Track {
    constructor(name = '', channel = 0) {
        this.name = name;
        this.channel = channel;      // 9 is drums, and is treated specially
        this.program = 0;
        this.volume = 100;
        this.muted = false;
        this.placements = [];
    }
    add(p) { this.placements.push(p); return p; }
}

class Song {
    constructor(name = 'Untitled') {
        this.name = name;
        this.bars = 1;               // bars per riff
        this.tempo = 120;
        this.loopStart = 0;          // in riffs
        this.loopEnd = 3;
        this.riffs = [];
        this.tracks = [];
    }
    get stepsPerRiff() { return this.bars * STEPS_PER_BAR; }
    get division() { return this.bars * 96; }
    get usPerQuarter() { return Math.floor(60000000 / this.tempo); }

    addRiff(r) { this.riffs.push(r); return r; }
    addTrack(t) { this.tracks.push(t); return t; }

    /// The first unused MIDI channel, or 9 when asking for drums. -1 if none
    /// is left — the original returns the same.
    freeChannel(drums = false) {
        const used = new Array(16).fill(false);
        for (const t of this.tracks) used[t.channel] = true;
        if (drums) return used[9] ? -1 : 9;
        for (let i = 0; i < 16; i++) if (!used[i] && i !== 9) return i;
        return -1;
    }

    /// Length in steps: the furthest point any placed riff reaches.
    get length() {
        let max = 0;
        for (const t of this.tracks)
            for (const p of t.placements) {
                const end = (p.at + p.riff.bars) * this.stepsPerRiff;
                if (end > max) max = end;
            }
        return max;
    }
}

// ── Reading and writing bytes ─────────────────────────────────────────────
// Java's DataOutputStream is big-endian, so this is too.

class Writer {
    constructor() { this.bytes = []; }
    u8(v)  { this.bytes.push(v & 0xFF); return this; }
    i32(v) { for (let s = 24; s >= 0; s -= 8) this.bytes.push((v >> s) & 0xFF); return this; }
    i64(v) {
        const b = BigInt(v);
        for (let s = 56n; s >= 0n; s -= 8n) this.bytes.push(Number((b >> s) & 0xFFn));
        return this;
    }
    raw(a) { for (const v of a) this.bytes.push(v & 0xFF); return this; }
    /// Java writes the CHARACTER count then the encoded bytes, which differ
    /// for anything non-ASCII. Reproduced rather than corrected: changing it
    /// would make files the original cannot read.
    str(s) {
        const enc = new TextEncoder().encode(s);
        this.i32(s.length).raw(enc);
        return this;
    }
    done() { return new Uint8Array(this.bytes); }
}

class Reader {
    constructor(buf) { this.b = new Uint8Array(buf); this.p = 0; }
    u8()  { return this.b[this.p++]; }
    i32() { const v = (this.b[this.p] << 24) | (this.b[this.p + 1] << 16)
                    | (this.b[this.p + 2] << 8) | this.b[this.p + 3];
            this.p += 4; return v; }
    i64() { let v = 0n;
            for (let i = 0; i < 8; i++) v = (v << 8n) | BigInt(this.b[this.p + i]);
            this.p += 8; return v; }
    raw(n) { const s = this.b.slice(this.p, this.p + n); this.p += n; return s; }
    str() { const n = this.i32(); return new TextDecoder().decode(this.raw(n)); }
}

// ── .vbm ──────────────────────────────────────────────────────────────────

function writeVbm(song) {
    const w = new Writer();
    w.i32(1);                        // format version
    w.str(song.name);
    w.i32(song.bars).i32(song.tempo).i32(song.loopStart).i32(song.loopEnd);

    w.i32(song.riffs.length);
    for (const r of song.riffs) {
        w.str(r.name).i32(r.bars).i64(r.id).i32(r.events.length);
        for (const e of r.events) {
            w.i32(e.tick).i32(e.status).i32(e.dur).i32(e.data.length).raw(e.data);
        }
    }

    w.i32(song.tracks.length);
    for (const t of song.tracks) {
        w.str(t.name).i32(t.channel).i32(t.program).i32(t.volume);
        w.i32(t.placements.length);
        for (const p of t.placements) w.i32(p.at).i64(p.riff.id);
    }
    return w.done();
}

function readVbm(buf) {
    const r = new Reader(buf);
    r.i32();                         // version, unused by the original too
    const song = new Song(r.str());
    song.bars = r.i32();
    song.tempo = r.i32();
    song.loopStart = r.i32();
    song.loopEnd = r.i32();

    const riffCount = r.i32();
    for (let i = 0; i < riffCount; i++) {
        const name = r.str(), bars = r.i32(), id = r.i64();
        const riff = new Riff(name, bars, id);
        const n = r.i32();
        for (let k = 0; k < n; k++) {
            const tick = r.i32(), status = r.i32(), dur = r.i32();
            const data = Array.from(r.raw(r.i32()));
            // Straight push: the file is already in tick order, and add()
            // would re-sort equal ticks into a different arrangement.
            riff.events.push(new Event(status, data, dur, tick));
        }
        song.addRiff(riff);
    }

    const trackCount = r.i32();
    for (let i = 0; i < trackCount; i++) {
        const t = new Track(r.str(), r.i32());
        t.program = r.i32();
        t.volume = r.i32();
        const n = r.i32();
        for (let k = 0; k < n; k++) {
            const at = r.i32(), id = r.i64();
            const riff = song.riffs.find(x => x.id === id);
            if (riff) t.add(new Placement(riff, at));   // a dangling id is dropped
        }
        song.addTrack(t);
    }
    return song;
}

// ── MIDI export ───────────────────────────────────────────────────────────

/// MIDI's variable-length quantity: seven bits per byte, high bit set on
/// every byte but the last.
function vlq(n) {
    const out = [n & 0x7F];
    while ((n >>>= 7) !== 0) out.unshift((n & 0x7F) | 0x80);
    return out;
}

/// Render to a standard MIDI file, format 1.
/// `from` and `to` are step positions, inclusive, as Vibe's exporter uses.
function writeMid(song, from = 0, to = null) {
    if (to === null) to = (song.loopEnd + 1) * song.stepsPerRiff - 1;

    const out = new Writer();
    out.raw([0x4D, 0x54, 0x68, 0x64, 0, 0, 0, 6, 0, 1]);   // MThd, len 6, format 1
    const n = song.tracks.length + 1;                       // +1 for the tempo track
    out.u8((n >> 8) & 0xFF).u8(n & 0xFF);
    out.u8((song.division >> 8) & 0xFF).u8(song.division & 0xFF);

    // Tempo track.
    const tempo = new Writer();
    const us = song.usPerQuarter;
    tempo.raw([0, 0xFF, 0x51, 3]);
    tempo.u8((us >> 16) & 0xFF).u8((us >> 8) & 0xFF).u8(us & 0xFF);
    tempo.raw([0, 0xFF, 0x2F, 0]);
    chunk(out, tempo.done());

    for (const t of song.tracks) {
        const body = new Writer();
        if (t.channel !== 9) body.raw([0, PROGRAM + t.channel, t.program & 0xFF]);
        body.raw([0, 176 + t.channel, 7, t.volume & 0xFF]);

        const ev = new Writer();
        let last = from;
        const pending = [];                   // note-offs, kept in tick order

        const flushTo = tick => {
            while (pending.length && pending[0].at <= tick) {
                const p = pending.shift();
                ev.raw(vlq((p.at - last) * TICKS_PER_STEP));
                last = p.at;
                ev.raw([p.status, p.pitch, p.velocity]);
            }
        };

        for (const pl of t.placements) {
            const base = pl.at * song.stepsPerRiff;
            for (const e of pl.riff.events) {
                const abs = base + e.tick;
                if (abs < from || abs > to) continue;
                flushTo(abs);
                ev.raw(vlq((abs - last) * TICKS_PER_STEP));
                last = abs;
                ev.raw([e.status + t.channel, ...e.data]);
                if (e.isNote) {
                    const off = { at: abs + e.dur, status: 128 + t.channel,
                                  pitch: e.data[0] & 0xFF, velocity: e.data[1] & 0xFF };
                    const i = pending.findIndex(p => off.at < p.at);
                    if (i === -1) pending.push(off); else pending.splice(i, 0, off);
                }
            }
        }

        // Anything still sounding is cut off at the end of the range.
        for (const p of pending) {
            if (p.at > to + 1) p.at = to + 1;
            ev.raw(vlq(Math.max(p.at - last, 0) * TICKS_PER_STEP));
            last = p.at;
            ev.raw([p.status, p.pitch, p.velocity]);
        }
        // Pad the track out to the full length with a silent event, so every
        // track ends together. The original uses a note-off on channel 9.
        if (last < to + 1) {
            ev.raw(vlq((to + 1 - last) * TICKS_PER_STEP));
            ev.raw([137, 0, 0]);
        }

        body.raw(ev.done());
        body.raw([0, 0xFF, 0x2F, 0]);
        chunk(out, body.done());
    }
    return out.done();
}

function chunk(out, body) {
    out.raw([0x4D, 0x54, 0x72, 0x6B]);       // MTrk
    out.u8((body.length >>> 24) & 0xFF).u8((body.length >>> 16) & 0xFF)
       .u8((body.length >>> 8) & 0xFF).u8(body.length & 0xFF);
    out.raw(body);
}
